name: smartish_lamp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  # Adds Cupertino Icons for iOS styling
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1  # Ensure this version exists and is compatible
  # Flutter Blue for BLE support
  flutter_blue_plus: ^1.32.12

  # Provider for state management (optional, but useful if your app grows)
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
